DROP TABLE IF EXISTS stock_warning;
DROP TABLE IF EXISTS stock_record;
DROP TABLE IF EXISTS purchase_order_item;
DROP TABLE IF EXISTS purchase_order;
DROP TABLE IF EXISTS product;
DROP TABLE IF EXISTS product_category;
DROP TABLE IF EXISTS user_account;

CREATE TABLE user_account (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL,
    real_name VARCHAR(64) NOT NULL,
    role VARCHAR(32) NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_user_role CHECK (role IN ('ADMIN', 'EMPLOYEE'))
);

CREATE TABLE product_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id BIGINT NOT NULL,
    name VARCHAR(128) NOT NULL,
    code VARCHAR(64) NOT NULL UNIQUE,
    unit VARCHAR(16) NOT NULL,
    current_stock INT NOT NULL DEFAULT 0,
    safe_stock INT NOT NULL DEFAULT 0,
    status TINYINT NOT NULL DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES product_category(id),
    CONSTRAINT chk_current_stock CHECK (current_stock >= 0),
    CONSTRAINT chk_safe_stock CHECK (safe_stock >= 0)
);

CREATE TABLE purchase_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    applicant_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    reason VARCHAR(255),
    approver_id BIGINT,
    approval_remark VARCHAR(255),
    approved_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_purchase_applicant FOREIGN KEY (applicant_id) REFERENCES user_account(id),
    CONSTRAINT fk_purchase_approver FOREIGN KEY (approver_id) REFERENCES user_account(id),
    CONSTRAINT chk_purchase_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'COMPLETED'))
);

CREATE TABLE purchase_order_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    remark VARCHAR(255),
    CONSTRAINT fk_purchase_item_order FOREIGN KEY (order_id) REFERENCES purchase_order(id),
    CONSTRAINT fk_purchase_item_product FOREIGN KEY (product_id) REFERENCES product(id),
    CONSTRAINT chk_purchase_item_quantity CHECK (quantity > 0)
);

CREATE TABLE stock_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    change_type VARCHAR(16) NOT NULL,
    quantity INT NOT NULL,
    before_stock INT NOT NULL,
    after_stock INT NOT NULL,
    source_type VARCHAR(32) NOT NULL,
    source_id BIGINT,
    operator_id BIGINT,
    remark VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stock_record_product FOREIGN KEY (product_id) REFERENCES product(id),
    CONSTRAINT fk_stock_record_operator FOREIGN KEY (operator_id) REFERENCES user_account(id),
    CONSTRAINT chk_stock_record_type CHECK (change_type IN ('IN', 'OUT')),
    CONSTRAINT chk_stock_record_quantity CHECK (quantity > 0),
    CONSTRAINT chk_stock_record_after CHECK (after_stock >= 0)
);

CREATE TABLE stock_warning (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL,
    warning_stock INT NOT NULL,
    safe_stock INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_stock_warning_product FOREIGN KEY (product_id) REFERENCES product(id),
    CONSTRAINT chk_stock_warning_status CHECK (status IN ('ACTIVE', 'RESOLVED'))
);
